apiVersion: cstation/v1
kind: Container
name: US02_traefik
enabled: true
image: traefik:latest
container_name: US02_traefik
network: PW_NET
ports:
- 110:110
- '25:25'
- 4190:4190
- 443:443
- 465:465
- 587:587
- 80:80
- 993:993
- 995:995
volumes:
- /var/run/docker.sock:/var/run/docker.sock
- /var/lib/traefik/letsencrypt:/letsencrypt
- /var/lib/traefik/conf:/etc/traefik/conf
- /var/lib/traefik/etc/traefik.yml:/etc/traefik/traefik.yml
- /var/lib/traefik/logs:/etc/traefik/logs
env:
  CF_API_KEY: 923abedd02920ce74104a899309bec1434d0c
  DHPARAM_GENERATION: 'false'
  CF_API_EMAIL: syner.catalyst@gmail.com
restart_policy: unless-stopped
