apiVersion: cstation/v1
kind: Container
name: US02_stalwart
enabled: true
image: stalwartlabs/stalwart:latest
container_name: US02_stalwart
network: PW_NET
volumes:
- /var/lib/stalwart/etc:/etc/stalwart
- /var/lib/stalwart/data:/var/lib/stalwart
- /var/lib/traefik/certs:/data/certs
env:
  STALWART_PUBLIC_URL: https://mail.ansis.com.sg
  STALWART_HEALTHCHECK_URL: https://127.0.0.1:443/healthz/live
restart_policy: unless-stopped
