apiVersion: cstation/v1
kind: Container
name: US02_portainer
enabled: true
image: portainer/portainer-ce:latest
container_name: US02_portainer
network: PW_NET
ports:
- 8000:8000
- 9000:9000
- 9443:9443
volumes:
- /var/run/docker.sock:/var/run/docker.sock
- /var/lib/portainer/data:/data
env:
  PORTAINER_LOG_LEVEL: INFO
restart_policy: always
