apiVersion: cstation/v1
kind: VPS
identity:
  name: us02.synercatalyst.com
  stage: prod
  region: manual
  provider: static
access:
  host: 152.53.169.95
  user: root
  port: 22
facts:
  os:
    id: ubuntu
    version: '26.04'
    pretty: Ubuntu 26.04 LTS
    kernel: 7.0.0-15-generic
    package_manager: apt
  cpu:
    architecture: aarch64
    vendor: ARM
    model: Neoverse-N1
    vcpu: 6
    sockets: 6
    threads_per_core: 1
  memory:
    total_mb: 7908
    used_mb: 2548
    available_mb: 5360
    swap_total_mb: 4095
    swap_used_mb: 1
  disks:
  - name: sr0
    size_gb: 1.0
    type: rom
  - name: vda
    size_gb: 256.0
    type: disk
    partitions:
    - name: vda1
      size_gb: 0.2
      type: part
      mountpoint: /boot/efi
    - name: vda2
      size_gb: 1.0
      type: part
      mountpoint: /boot
    - name: vda3
      size_gb: 254.7
      type: part
      mountpoint: /
  network:
    interfaces:
    - name: eth0
      state: UP
      mac: 56:1d:1f:8e:88:bf
      ipv4: 152.53.169.95
      ipv4_prefix: 22
      ipv6: 2a0a:4cc0:2000:aebf:541d:1fff:fe8e:88bf
      ipv6_prefix: 64
    - name: docker0
      state: DOWN
      mac: c2:d7:98:77:4c:04
      ipv4: 172.17.0.1
      ipv4_prefix: 16
    - name: br-bbc08d5e66cc
      state: DOWN
      mac: 4e:04:a4:f0:e5:4e
      ipv4: 172.19.0.1
      ipv4_prefix: 16
    - name: br-5af7f18e305a
      state: UP
      mac: a6:d4:47:49:62:b6
      ipv4: 172.18.0.1
      ipv4_prefix: 16
    - name: veth888049c
      state: UP
      mac: 1e:cc:a4:b3:a9:60
    - name: vethc6a089f
      state: UP
      mac: f2:de:27:81:4f:0c
    - name: veth13fb560
      state: UP
      mac: 3e:46:20:f0:b0:a4
    - name: vethab3ddf9
      state: UP
      mac: b2:5c:a2:27:f3:06
    routes:
    - destination: default
      via: 152.53.168.1
      dev: eth0
    - destination: 152.53.168.0/22
      dev: eth0
    - destination: 172.17.0.0/16
      dev: docker0
    - destination: 172.18.0.0/16
      dev: br-5af7f18e305a
    - destination: 172.19.0.0/16
      dev: br-bbc08d5e66cc
  hostname: us02.synercatalyst.com
  packages:
    detected:
    - openssh-server
    - ufw
    - nftables
    - fail2ban
    - docker.io
    - containerd
    - docker-compose-v2
    - python3
    - rsync
    - curl
    - git
    - sudo
    missing:
    - docker
os:
  baseline:
    packages: []
    sshd:
      disable_password_auth: true
    firewall:
      mode: ufw
      allow:
      - 22/tcp
