apiVersion: cstation/v1
kind: VPS
identity:
  name: sg07.ansis.com.sg
  stage: prod
  region: sin
access:
  host: 5.223.74.96
  user: root
  port: 22
facts:
  os:
    id: ubuntu
    version: '24.04'
    pretty: Ubuntu 24.04.4 LTS
    kernel: 6.8.0-110-generic
    package_manager: apt
  cpu:
    architecture: x86_64
    vendor: AuthenticAMD
    model: AMD EPYC-Genoa Processor
    vcpu: 4
    cores_per_socket: 4
    sockets: 1
    threads_per_core: 1
  memory:
    total_mb: 7745
    used_mb: 4905
    available_mb: 2840
    swap_total_mb: 0
    swap_used_mb: 0
  disks:
  - name: sda
    size_gb: 152.6
    type: disk
    partitions:
    - name: sda1
      size_gb: 152.3
      type: part
      mountpoint: /
    - name: sda14
      size_gb: 0.0
      type: part
    - name: sda15
      size_gb: 0.2
      type: part
      mountpoint: /boot/efi
  - name: sr0
    size_gb: 1.0
    type: rom
  network:
    interfaces:
    - name: eth0
      state: UP
      mac: 92:00:06:b2:e0:33
      ipv4: 5.223.74.96
      ipv4_prefix: 32
      ipv6: 2a01:4ff:2f0:2dad::1
      ipv6_prefix: 64
    - name: docker0
      state: UP
      mac: f6:52:bb:0b:54:43
      ipv4: 172.17.0.1
      ipv4_prefix: 16
    - name: br-f9456126d133
      state: UP
      mac: e2:a6:4f:cb:ca:e1
      ipv4: 172.18.0.1
      ipv4_prefix: 16
    - name: veth77ee686
      state: UP
      mac: d6:29:20:f4:c2:3b
    - name: vethac4cc0a
      state: UP
      mac: 5e:c4:a8:57:0a:08
    - name: veth8e94e62
      state: UP
      mac: da:9d:ba:84:6c:33
    - name: veth458511c
      state: UP
      mac: e2:05:fe:91:62:ac
    - name: veth15d8184
      state: UP
      mac: 0a:95:bd:97:48:c5
    - name: vethca566e2
      state: UP
      mac: 0a:f7:1b:67:dd:bd
    routes:
    - destination: default
      via: 172.31.1.1
      dev: eth0
    - destination: 172.17.0.0/16
      dev: docker0
    - destination: 172.18.0.0/16
      dev: br-f9456126d133
    - destination: 172.31.1.1
      dev: eth0
    - destination: 185.12.64.1
      via: 172.31.1.1
      dev: eth0
    - destination: 185.12.64.2
      via: 172.31.1.1
      dev: eth0
  hostname: sg07
  packages:
    detected:
    - openssh-server
    - ufw
    - nftables
    - docker.io
    - containerd
    - python3
    - rsync
    - curl
    - git
    - sudo
    missing:
    - fail2ban
    - docker
os:
  baseline:
    packages:
    - fail2ban
    sshd:
      disable_password_auth: true
    firewall:
      mode: ufw
      allow:
      - 22/tcp
