- url: git@github.com:lohwswilson/mukit-odoo-modules.git
  branch: 17.0
  includes:
    - muk_web_theme
    - muk_product
    - muk_web_colors
    - muk_web_appsbar
    - muk_web_dialog
    - muk_web_chatter


- url: git@github.com:lohwswilson/queue.git
  branch: 17.0
  includes:
    - queue_job
    - queue_job_cron_jobrunner

- url: git@github.com:lohwswilson/server-tools.git
  branch: 17.0
  includes:
    - views_migration_17

- url: git@github.com:lohwswilson/web.git
  branch: 17.0
  includes:
    - web_refresher

- url: git@github.com:lohwswilson/social.git
  branch: 17.0
  includes:
    - mail_gateway
    - mail_gateway_whatsapp
    - mail_gateway_telegram
