- name: Install Portainer Docker Management Console
  hosts: all
  become: yes

  tasks:

    - name: Pull Portainer Latest Image
      docker_image:
        name: portainer/portainer-ce
        source: pull


    - name: Create PW Application Network
      docker_network:
        name: PW_NET

    - name: Create Portainer Container 
      docker_container:
        name: "{{ portainer_container }}_CE"
        image: portainer/portainer-ce:latest
        state: started
        restart: yes
        restart_policy: always
        networks:
          - name: '{{ docker_PW_network }}'
        networks_cli_compatible: yes
        ports:
          - "8000:8000"
          - "9000:9000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - "/var/lib/perfectwork/{{ inventory_hostname|upper }}/CONTAINERS/{{ inventory_hostname|upper }}_PORTAINER_CE:/data"
