---
- name: Sync multiple forked GitHub repositories with their upstream
  hosts: localhost
  vars:
    repos:
      - name: Odoo 18
        fork_url: "git@github.com:ansis-ai/odoo"
        upstream_url: "https://github.com/odoo/odoo.git"  # Add upstream
        local_dir: "/opt/PW/PW.18.0"
        branch: "18.0"

      - name: Odoo 17
        fork_url: "git@github.com:ansis-ai/odoo"
        upstream_url: "https://github.com/odoo/odoo.git"  # Add upstream
        local_dir: "/opt/PW/PW.7.0"
        branch: "17.0"

      - name: Odoo 16
        fork_url: "git@github.com:ansis-ai/odoo"
        upstream_url: "https://github.com/odoo/odoo.git"  # Add upstream
        local_dir: "/opt/PW/PW.6.0"
        branch: "16.0"
