#! /usr/local/bin/ansible-playbook

---
  - hosts: all
    become: yes
    vars:
      # ansible_python_interpreter: /usr/bin/python3
    tasks:

      - name: Pull Portainer Latest Image
        docker_image:
          name: portainer/portainer-ce
          source: pull


      - name: Create a network
        docker_network:
          name: PW_NET

      # Create Portainer Volume
      # - name: Create Portainer volume
      #  docker_volume:
      #    name: portainer_data

      - name: Create Portainer Container
        docker_container:
          name: "{{ inventory_hostname|upper }}_PORTAINER"
          image: portainer/portainer-ce:latest
          state: started
          restart: yes
          restart_policy: always
          networks:
            - name: PW_NET
          networks_cli_compatible: yes
          ports:
            - "8000:8000"
            - "9000:9000"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - "/var/lib/perfectwork/{{ inventory_hostname|upper }}/CONTAINERS/{{ inventory_hostname|upper }}_PORTAINER_CE:/data"
