apiVersion: cstation/v1
kind: Stack
name: mailcow
enabled: false
git_repo: "https://github.com/mailcow/mailcow-dockerized"
git_branch: master
git_dir: /opt/mailcow
network: PW_NET
env:
  SKIP_LETS_ENCRYPT: "y"
  SKIP_NGINX: "y"
  HTTP_PORT: "8082"
  HTTPS_PORT: "8443"
  MAILCOW_HOSTNAME: "mail.synercatalyst.com"
  TZ: "UTC"