http:
  # Add the router
  routers:
    perfectwork_app:
      entryPoints:
      - web
      - websecure
      service: US01_SYNER_US01DB@docker
      rule: Host(`perfectwork.app`)
      tls:
        certResolver: le_resolver
